# Generated by Django 6.0.6 on 2026-08-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0003_alter_customer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
